[project]
name = "middleground-robot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiomysql>=0.3.2",
    "concurrent-log-handler>=0.9.29",
    "deepagents>=0.6.12",
    "dotenv>=0.9.9",
    "greenlet>=3.5.4",
    "httpx>=0.28.1",
    "ipykernel>=7.3.0",
    "langchain-deepseek",
    "langchain-mcp-adapters>=0.3.2",
    "langgraph-checkpoint-postgres>=3.1.0",
    "pandas>=3.0.5",
    "psycopg[binary]>=3.3.4",
    "pycryptodome>=3.23.0",
    "redis>=8.0.1",
    "setuptools>=83.0.0",
    "sqlalchemy>=2.0.51",
    "tavily-python>=0.7.26",
]
